### ISSUE TITLE
Questions about 2-pimd_basics.ipynb

### ISSUE THREAD

**Issue by brucefan1983** [i-pi/pimd-mooc#1]
Dear developers,

Thanks for providing the nice tutorials. I played with the Jupyter notebook `2-pimd_basics.ipynb` and have a few questions:
- It seems the implementation has not strictly followed the reference [Ceriotti et al., J. Chem. Phys. 133, 124104 (2010)]. For example, the order of the normal modes is changed and some signs here and there are also changed (perhaps this is due to the change of order?) Is the implementation here mathematically equivalent to the algorithm as presented in the reference?
- I have difficulty to understand the $j$ index of the transformation matrix $T_{jk}$. It is clear that $k$ runs from 0 to $P-1$, but how about $j$? Does it run from 0 to $P-1$ or from 1 to $P$. From the Reference, it seems to be from 1 to $P$, as the summation over $j$ is always written as $\sum_{j=1}$.
- Perhaps equation (3) in the notebook has a typo? $\frac{1}{\omega_k \Delta t}$ should be $\frac{1}{m\omega_k}$?
- If I put the initial centroid position to a nonzero value, say -1, using
```
q = np.linspace(-1,-1,P)
```
  then the centroid position is always there (see the figure below). Is this correct? My expectation is that the centroid should oscillate about the energy minimum. Do I have a misunderstanding here?
![image](https://user-images.githubusercontent.com/24891193/226134110-5fad9959-8ff0-4208-b458-d94ee47d09fb.png)
- Similarly, my understanding is that if the initial centroid velocity is nonzero (which is usually the case using random numbers), the centroid position should also oscillate rather than keeping unchanged. Am I wrong here?

**Comment by mahrossi** [comment]
Hi @brucefan1983 - I believe @eszterpos addressed all your comments and fixed a typo in the equations that led to the "fixed" centroid. Thanks for catching that! @eszterpos , could you please answer in detail?

**Comment by brucefan1983** [comment]
Thanks @mahrossi for the kind reply. After the changes, I understand more about the methods. However, I am still puzzled by a sign in `freeRPProp`:

```
freeRPProp[0,1,k] = m*omega[k]*np.sin(omega[k]*dt)
```
In Eq. (3) of the notebook (and in the 2010 JCP paper), there is a minus sign before `m`.  Is there still a typo in the code or I missed something here?

**Comment by eszterpos** [comment]
Hello @brucefan1983,
Thanks very much for your comments and feedback, it was very helpful and we really appreciate it.
Let me go point by point regarding your comments.

- You are right, our implementation does not follow the referenced Ceriotti paper one-to-one. This has been a personal choice, the one that we found works simplest when setting up the normal mode arrays. It is important to note that as long as one keeps track of which index of the array corresponds to which normal mode they should be fine (even if they are relatively in a mixed order when compared to the referenced paper). Where should you be very careful wrt. bookkeeping? For instance at the normal mode propagation of the free particle propagator. 

- The index _j_ indices the normal modes, differentiating between the plus/minus modes and the centroid mode. As we said before, many different implementations exist that are consistent with the mathematical formulation of the reference. (just as there are many mathematically equivalent ways of choosing the indeces, too). However, consistency is very important within the code itself. This brings us to your following points, which were pointing out indeed bugs in the code, and which should be all fixed now. 
 
Many thanks for noting them and coming back to us this fast.

**Comment by brucefan1983** [comment]
Thanks for the clarification, which is very helpful. I have tried to implement it strictly following the Reference and can get similar results. And the `j` indexing is not important which should be due to the cyclic properties of the normal modes (Fourier transform).

I will close this issue. Thanks again for you help!
